### ISSUE TITLE
Assistance getting working

### ISSUE THREAD

**Issue by justinglock40** [AndrewHolmes060/Plex-Preroll-Builder#9]
So I've been trying to get this going. the app starts listening, I go refresh metadata, but nothing is generated. No logs/files. Can you help?

**Comment by HolmesBrew** [comment]
ah your right because of the webhook functionality its changed the way it generates the trailer so its only on the library.new webhook. if you want to test it out change line 176 from library.new to media.play and then re run it all watch a film and itll generate it.

**Comment by justinglock40** [comment]
I'm not able to test it out at the moment. 

-Does the full film have to be watched to trigger the webhook? 

-Can the README be more detailed?

With maybe screenshots of how the config should look. It's kind of confusing because what you see in preroll.py is different from what its written on README

Also in the README on the headless pip install. There's a typo that says `pgit` but should be `git`
and in the preroll. py https://github.com/AndrewHolmes060/Plex-Preroll-Builder/blob/8f8e37e2b98038ec2154c3ce5553738aee26ccea/preroll.py#L164 has a typo `/plexpreoll` should be `/plexpreroll`

**Comment by HolmesBrew** [comment]
you dont need to watch a whole fil aslong as you play it from fresh it should fire the media.play webhook to the python script  assuming the webhook url is correct on your server side 
https://support.plex.tv/articles/115002267687-webhooks/
ive also updated the readme with pictures.

**Comment by justinglock40** [comment]
Can you do a example screen of your config? Mine is still not registering the hooks

**Comment by HolmesBrew** [comment]
im sorry im not really sure what you mean? the code is the same code that i put into the github and i uploaded a few screenshots of it in the readme everything else is just going to the file and opening it with python3 and it starts. ive set up an env file for each of the variables but if your inputting your own information in that as per the readme it should work. what errors/output is it your getting.

**Comment by justinglock40** [comment]
Not getting any errors. just nothing happens lol. Where is the env file?

**Comment by HolmesBrew** [comment]
.env files tend to be used to emulate an enviroment so that i can put in enviromental variables and it gets skipped due to having sensitive information in. the .env file only has the variables that in the readme we manually set in the script

baseurl = 'Input Your Plex URL'
token = 'Input Your Plex Token'
folder = "Input the directory that this is going to sit in"

**Comment by justinglock40** [comment]
So set the variables here? 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/23133649/120720262-c4756380-c499-11eb-93aa-96339747f2be.png">

and what is  this referencing? folder = "Input the directory that this is going to sit in" `preroll.py` or `/prerolls/` folder?

**Comment by justinglock40** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/23133649/120720452-19b17500-c49a-11eb-8dae-cca8d6094273.png">


Like this?

**Comment by HolmesBrew** [comment]
yeah step 5 in the readme is listing the variables you need to change. including the token and the folder. just change them to strings. so it would be

5. configure preroll.py to your plex server
change the below fields to the details of your plex server

baseurl = 'Input Your Plex URL'
token = 'Input Your Plex Token'
folder = "Input the directory that this is going to sit in"

the plex server will be the ip address. and the token will be your own personal token.
you will also need to remove the os.environ.get() so that it looks the same as above but with your personal details.
 
the folder is /Users/user/Documents/GitHub/Plex-Preroll-Builder/

**Comment by justinglock40** [comment]
Still not working for me do you need to forward port 5000 in the router?

**Comment by HolmesBrew** [comment]
You shouldnt have too. is your server on the same network as you or
elsewhere? If it's local try changing your webhook Url to reflect the local
IP. E.g. 127.0.0.1/plexpreroll

**Comment by justinglock40** [comment]
Plex is in a Docker container.

**Comment by justinglock40** [comment]
So it's trying to send now based on plex log but not getting there?

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/23133649/120732398-3d34e980-c4b3-11eb-9b9f-54c21bb3d21f.png">

**Comment by justinglock40** [comment]
Closing. Webhooks are being registered with latest commits.
